name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allow manual triggers

jobs:
  daily-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add a file or make changes (Example: Update README)
        run: |
          echo "Last updated: $(date)" >> README.md

      - name: Commit changes with susmitha.ganesan@straive.com
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated daily update"
          commit_options: '--no-gpg-sign'
          file_pattern: 'README.md'
          commit_author: 'Susmitha Ganesan <susmitha.ganesan@straive.com>'
