name: Automated Daily Commit

on:
  schedule:
    # Runs every day at 01:00 AM UTC
    - cron: '0 1 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Make a change (if needed)
      run: echo "Last updated: $(date)" >> update-log.txt

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email susmitha.ganesan@straive.com

    - name: Commit Changes
      run: |
        git add update-log.txt
        git commit -m "Daily update: $(date)" || echo "No changes to commit"

    - name: Push Changes
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push
